def convertstr(wtc, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z):
  for i in a:
    wtc = wtc.replace(i, 'a')
  for i in b:
    wtc = wtc.replace(i, 'b')
  for i in c:
    wtc = wtc.replace(i, 'c')
  for i in d:
    wtc = wtc.replace(i, 'd')
  for i in e:
    wtc = wtc.replace(i, 'e')
  for i in f:
    wtc = wtc.replace(i, 'f')
  for i in g:
    wtc = wtc.replace(i, 'g')
  for i in h:
    wtc = wtc.replace(i, 'h')
  for i in i:
    wtc = wtc.replace(i, 'i')
  for i in j:
    wtc = wtc.replace(i, 'j')
  for i in k:
    wtc = wtc.replace(i, 'k')
  for i in l:
    wtc = wtc.replace(i, 'l')
  for i in m:
    wtc = wtc.replace(i, 'm')
  for i in n:
    wtc = wtc.replace(i, 'n')
  for i in o:
    wtc = wtc.replace(i, 'o')
  for i in p:
    wtc = wtc.replace(i, 'p')
  for i in q:
    wtc = wtc.replace(i, 'q')
  for i in r:
    wtc = wtc.replace(i, 'r')
  for i in s:
    wtc = wtc.replace(i, 's')
  for i in t:
    wtc = wtc.replace(i, 't')
  for i in u:
    wtc = wtc.replace(i, 'u')
  for i in w:
    wtc = wtc.replace(i, 'w')
  for i in x:
    wtc = wtc.replace(i, 'x')
  for i in y:
    wtc = wtc.replace(i, 'y')  
  for i in z:
    wtc = wtc.replace(i, 'z')
  return wtc